get_miners_pages-f2:
	DEBUG=app ts-node get_miners_pages-f2pool.ts

get_miners_pages-ad:
	DEBUG=app ts-node get_miners_pages-asic-dex.ts

get_miners_data-ad:
	ts-node get_miners_data-asic-dex.ts

get_miners_data-f2:
	ts-node get_miners_data-f2pool.ts

merge_miners_data:
	ts-node merge_miners_data.ts